Specify user root for apk
apk now spits out this error unless an explicit root
user is specified:

ERROR: Failed to open apk database: Permission denied

(Could be a change in the Alpine based base image, or in docker
 behavior, I'm not sure)

Signed-off-by: Gunnar Andersson <gandersson@genivi.org>